# Generated by Django 5.0.6 on 2024-06-11 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_empty'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField(verbose_name='Game ID')),
                ('team_id', models.IntegerField(blank=True, null=True, verbose_name='Team ID')),
                ('player_license_id', models.IntegerField(blank=True, null=True, verbose_name='Player License ID')),
                ('action_time', models.CharField(max_length=8, verbose_name='Action Time')),
                ('action_type', models.IntegerField(verbose_name='Action Type')),
            ],
        ),
    ]
